#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

apk add x11vnc x11vnc-doc xvfb xterm xorg-server xf86-video-dummy \
	    i3wm i3wm-doc i3lock i3lock-doc i3status i3status-doc xdpyinfo \
	        xdpyinfo-doc ttf-dejavu

echo "Creating directories and writing config files"

if [ ! -e /etc/X11/xorg.conf.d ]; then
    mkdir -p /etc/X11/xorg.conf.d
fi

cat <<HERE >/etc/X11/xorg.conf.d/10-headless.conf
Section "Monitor"
        Identifier "dummy_monitor"
        HorizSync 28.0-80.0
        VertRefresh 48.0-75.0
	DisplaySize  250 174    # In millimeters, iPad gen 7 & 8
EndSection

Section "Device"
        Identifier "dummy_card"
        VideoRam 256000
        Driver "dummy"
EndSection

Section "Screen"
        Identifier "dummy_screen"
        Device "dummy_card"
        Monitor "dummy_monitor"
        SubSection "Display"
	   depth 24
	   Modes "1024x768"  # Works OK on ~10 inch iPad's
#	   Modes "1280x1024"  # Likely to work on larger iPads
	EndSubSection
EndSection
HERE

if [ ! -e /home/marcos/i3logs ]; then
    mkdir /home/marcos/i3logs
    chown ish.ish /home/marcos/i3logs
fi

cat <<THERE >/home/marcos/.xinitrc
xrdb -merge ~/.Xresources
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
exec i3 -V >> ~/i3logs/i3log-$(date +'%F-%k-%M-%S') 2>&1
THERE

chown ish.ish /home/marcos/.xinitrc

cat <<EVERYWHERE >/home/marcos/.Xresources
Xft.dpi: 264
xterm*VT100.Translations: #override \
    Ctrl <Key> minus: smaller-vt-font() \\n\
    Ctrl <Key> plus: larger-vt-font() \\n\
    Ctrl <Key> 0: set-vt-font(d)
EVERYWHERE

chown ish.ish /home/marcos/.Xresources

cat <<BEATLES >/etc/X11/Xwrapper.config
allowed_users = anybody
BEATLES

echo "------------------------------------------------------"
echo "VNC has been enabled.  To start the VNC server run..."
echo "------------------------------------------------------"
echo
echo "vnc-start"
