# create a workflow that runs on ubuntu 32 bit and runs docker build to generate
# an image the output of this workflow is a tar file that can be used as an
# image in the iSH app
#

name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker image import default/alpine.tar.gz alpinish:0.0
          docker build --no-cache -t x86_ish_alpine .

      - name: Convert image to tar
        run: |
          docker run --privileged --name test x86_ish_alpine sh
          docker cp test:/tmp/ish-fs.tar.gz alpinish.tar.gz

      - name: Generate artifact name
        id: generate-name
        run: |
          echo "name=alpinish-$(git describe --tags --abbrev=0 2>/dev/null || echo nightly)" >> $GITHUB_ENV

      - name: Upload image
        id: create_release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}.tar.gz
          path: alpinish.tar.gz

      - name: Release image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: alpinish.tar.gz
          asset_name: ${{ env.name }}.tar.gz
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/gzip

